//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inzhener5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Клиенты CustomAttributes)

    // *** End programmer edit section *** (Клиенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентыE", new string[] {
            "ФИО as \'ФИО\'",
            "Номер_телефона as \'Номер_телефона\'"})]
    [View("КлиентыL", new string[] {
            "ФИО as \'ФИО\'",
            "Номер_телефона as \'Номер_телефона\'"})]
    public class Клиенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fНомер_телефона;
        
        private IIS.Inzhener5.ЗакМенеджера fЗакМенеджера;
        
        // *** Start programmer edit section *** (Клиенты CustomMembers)

        // *** End programmer edit section *** (Клиенты CustomMembers)

        
        /// <summary>
        /// Номер_телефона.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Номер_телефона CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Номер_телефона CustomAttributes)
        public virtual int Номер_телефона
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Номер_телефона Get start)

                // *** End programmer edit section *** (Клиенты.Номер_телефона Get start)
                int result = this.fНомер_телефона;
                // *** Start programmer edit section *** (Клиенты.Номер_телефона Get end)

                // *** End programmer edit section *** (Клиенты.Номер_телефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Номер_телефона Set start)

                // *** End programmer edit section *** (Клиенты.Номер_телефона Set start)
                this.fНомер_телефона = value;
                // *** Start programmer edit section *** (Клиенты.Номер_телефона Set end)

                // *** End programmer edit section *** (Клиенты.Номер_телефона Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ФИО CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ФИО Get start)

                // *** End programmer edit section *** (Клиенты.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Клиенты.ФИО Get end)

                // *** End programmer edit section *** (Клиенты.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ФИО Set start)

                // *** End programmer edit section *** (Клиенты.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Клиенты.ФИО Set end)

                // *** End programmer edit section *** (Клиенты.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Клиенты.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ЗакМенеджера CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ЗакМенеджера CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗакМенеджера"})]
        [NotNull()]
        public virtual IIS.Inzhener5.ЗакМенеджера ЗакМенеджера
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ЗакМенеджера Get start)

                // *** End programmer edit section *** (Клиенты.ЗакМенеджера Get start)
                IIS.Inzhener5.ЗакМенеджера result = this.fЗакМенеджера;
                // *** Start programmer edit section *** (Клиенты.ЗакМенеджера Get end)

                // *** End programmer edit section *** (Клиенты.ЗакМенеджера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ЗакМенеджера Set start)

                // *** End programmer edit section *** (Клиенты.ЗакМенеджера Set start)
                this.fЗакМенеджера = value;
                // *** Start programmer edit section *** (Клиенты.ЗакМенеджера Set end)

                // *** End programmer edit section *** (Клиенты.ЗакМенеджера Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыE", typeof(IIS.Inzhener5.Клиенты));
                }
            }
            
            /// <summary>
            /// "КлиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыL", typeof(IIS.Inzhener5.Клиенты));
                }
            }
        }
    }
}
