//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inzhener5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенклатура.
    /// </summary>
    // *** Start programmer edit section *** (Номенклатура CustomAttributes)

    // *** End programmer edit section *** (Номенклатура CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменклатураE", new string[] {
            "Товар as \'Товар\'"})]
    [View("НоменклатураL", new string[] {
            "Товар as \'Товар\'"})]
    public class Номенклатура : ICSSoft.STORMNET.DataObject
    {
        
        private string fТовар;
        
        private IIS.Inzhener5.Инженер fИнженер;
        
        private IIS.Inzhener5.ЗакМенеджера fЗакМенеджера;
        
        private IIS.Inzhener5.ОтчетОТестПК fОтчетОТестПК;
        
        // *** Start programmer edit section *** (Номенклатура CustomMembers)

        // *** End programmer edit section *** (Номенклатура CustomMembers)

        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Товар CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Товар CustomAttributes)
        [StrLen(255)]
        public virtual string Товар
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Товар Get start)

                // *** End programmer edit section *** (Номенклатура.Товар Get start)
                string result = this.fТовар;
                // *** Start programmer edit section *** (Номенклатура.Товар Get end)

                // *** End programmer edit section *** (Номенклатура.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Товар Set start)

                // *** End programmer edit section *** (Номенклатура.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Номенклатура.Товар Set end)

                // *** End programmer edit section *** (Номенклатура.Товар Set end)
            }
        }
        
        /// <summary>
        /// Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.ЗакМенеджера CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.ЗакМенеджера CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗакМенеджера"})]
        [NotNull()]
        public virtual IIS.Inzhener5.ЗакМенеджера ЗакМенеджера
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.ЗакМенеджера Get start)

                // *** End programmer edit section *** (Номенклатура.ЗакМенеджера Get start)
                IIS.Inzhener5.ЗакМенеджера result = this.fЗакМенеджера;
                // *** Start programmer edit section *** (Номенклатура.ЗакМенеджера Get end)

                // *** End programmer edit section *** (Номенклатура.ЗакМенеджера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.ЗакМенеджера Set start)

                // *** End programmer edit section *** (Номенклатура.ЗакМенеджера Set start)
                this.fЗакМенеджера = value;
                // *** Start programmer edit section *** (Номенклатура.ЗакМенеджера Set end)

                // *** End programmer edit section *** (Номенклатура.ЗакМенеджера Set end)
            }
        }
        
        /// <summary>
        /// Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Инженер CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Инженер CustomAttributes)
        [PropertyStorage(new string[] {
                "Инженер"})]
        [NotNull()]
        public virtual IIS.Inzhener5.Инженер Инженер
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Инженер Get start)

                // *** End programmer edit section *** (Номенклатура.Инженер Get start)
                IIS.Inzhener5.Инженер result = this.fИнженер;
                // *** Start programmer edit section *** (Номенклатура.Инженер Get end)

                // *** End programmer edit section *** (Номенклатура.Инженер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Инженер Set start)

                // *** End programmer edit section *** (Номенклатура.Инженер Set start)
                this.fИнженер = value;
                // *** Start programmer edit section *** (Номенклатура.Инженер Set end)

                // *** End programmer edit section *** (Номенклатура.Инженер Set end)
            }
        }
        
        /// <summary>
        /// Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.ОтчетОТестПК CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.ОтчетОТестПК CustomAttributes)
        [PropertyStorage(new string[] {
                "ОтчетОТестПК"})]
        [NotNull()]
        public virtual IIS.Inzhener5.ОтчетОТестПК ОтчетОТестПК
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.ОтчетОТестПК Get start)

                // *** End programmer edit section *** (Номенклатура.ОтчетОТестПК Get start)
                IIS.Inzhener5.ОтчетОТестПК result = this.fОтчетОТестПК;
                // *** Start programmer edit section *** (Номенклатура.ОтчетОТестПК Get end)

                // *** End programmer edit section *** (Номенклатура.ОтчетОТестПК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.ОтчетОТестПК Set start)

                // *** End programmer edit section *** (Номенклатура.ОтчетОТестПК Set start)
                this.fОтчетОТестПК = value;
                // *** Start programmer edit section *** (Номенклатура.ОтчетОТестПК Set end)

                // *** End programmer edit section *** (Номенклатура.ОтчетОТестПК Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменклатураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураE", typeof(IIS.Inzhener5.Номенклатура));
                }
            }
            
            /// <summary>
            /// "НоменклатураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураL", typeof(IIS.Inzhener5.Номенклатура));
                }
            }
        }
    }
}
