//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inzhener5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет о тест ПК.
    /// </summary>
    // *** Start programmer edit section *** (ОтчетОТестПК CustomAttributes)

    // *** End programmer edit section *** (ОтчетОТестПК CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о тест ПК")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетОТестПКE", new string[0])]
    [View("ОтчетОТестПКL", new string[0])]
    public class ОтчетОТестПК : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (ОтчетОТестПК CustomMembers)

        // *** End programmer edit section *** (ОтчетОТестПК CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетОТестПКE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОТестПКE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОТестПКE", typeof(IIS.Inzhener5.ОтчетОТестПК));
                }
            }
            
            /// <summary>
            /// "ОтчетОТестПКL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОТестПКL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОТестПКL", typeof(IIS.Inzhener5.ОтчетОТестПК));
                }
            }
        }
    }
}
