//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inzhener5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "ФИО as \'ФИО\'",
            "Номер_Телефона as \'Номер_ телефона\'"})]
    [View("СотрудникиL", new string[] {
            "ФИО as \'ФИО\'",
            "Номер_Телефона as \'Номер_ телефона\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private string fНомер_Телефона;
        
        private IIS.Inzhener5.ЗакМенеджера fЗакМенеджера;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// Номер_Телефона.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Номер_Телефона CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Номер_Телефона CustomAttributes)
        [StrLen(255)]
        public virtual string Номер_Телефона
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Номер_Телефона Get start)

                // *** End programmer edit section *** (Сотрудники.Номер_Телефона Get start)
                string result = this.fНомер_Телефона;
                // *** Start programmer edit section *** (Сотрудники.Номер_Телефона Get end)

                // *** End programmer edit section *** (Сотрудники.Номер_Телефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Номер_Телефона Set start)

                // *** End programmer edit section *** (Сотрудники.Номер_Телефона Set start)
                this.fНомер_Телефона = value;
                // *** Start programmer edit section *** (Сотрудники.Номер_Телефона Set end)

                // *** End programmer edit section *** (Сотрудники.Номер_Телефона Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Get start)

                // *** End programmer edit section *** (Сотрудники.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудники.ФИО Get end)

                // *** End programmer edit section *** (Сотрудники.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Set start)

                // *** End programmer edit section *** (Сотрудники.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудники.ФИО Set end)

                // *** End programmer edit section *** (Сотрудники.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ЗакМенеджера CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ЗакМенеджера CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗакМенеджера"})]
        [NotNull()]
        public virtual IIS.Inzhener5.ЗакМенеджера ЗакМенеджера
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ЗакМенеджера Get start)

                // *** End programmer edit section *** (Сотрудники.ЗакМенеджера Get start)
                IIS.Inzhener5.ЗакМенеджера result = this.fЗакМенеджера;
                // *** Start programmer edit section *** (Сотрудники.ЗакМенеджера Get end)

                // *** End programmer edit section *** (Сотрудники.ЗакМенеджера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ЗакМенеджера Set start)

                // *** End programmer edit section *** (Сотрудники.ЗакМенеджера Set start)
                this.fЗакМенеджера = value;
                // *** Start programmer edit section *** (Сотрудники.ЗакМенеджера Set end)

                // *** End programmer edit section *** (Сотрудники.ЗакМенеджера Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Inzhener5.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Inzhener5.Сотрудники));
                }
            }
        }
    }
}
