//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inzhener5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч отчет о тест ПК.
    /// </summary>
    // *** Start programmer edit section *** (ТЧОтчетОТестПК CustomAttributes)

    // *** End programmer edit section *** (ТЧОтчетОТестПК CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч отчет о тест ПК")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧОтчетОТестПКE", new string[] {
            "Тестируемые_приложения_и_игры as \'Тестируемые_приложения_и_игры\'",
            "Операционная_система as \'Операционная_система\'",
            "результаты_тестирования as \'Результаты_тестирования\'",
            "Выводы_и_рекомендации as \'Выводы_и_рекомендации\'"})]
    [View("ТЧОтчетОТестПКL", new string[] {
            "Тестируемые_приложения_и_игры as \'Тестируемые_приложения_и_игры\'",
            "Операционная_система as \'Операционная_система\'",
            "результаты_тестирования as \'Результаты_тестирования\'",
            "Выводы_и_рекомендации as \'Выводы_и_рекомендации\'"})]
    public class ТЧОтчетОТестПК : ICSSoft.STORMNET.DataObject
    {
        
        private string fТестируемые_приложения_и_игры;
        
        private string fОперационная_система;
        
        private string fрезультаты_тестирования;
        
        private string fВыводы_и_рекомендации;
        
        private IIS.Inzhener5.ОтчетОТестПК fОтчетОТестПК;
        
        // *** Start programmer edit section *** (ТЧОтчетОТестПК CustomMembers)

        // *** End programmer edit section *** (ТЧОтчетОТестПК CustomMembers)

        
        /// <summary>
        /// Выводы_и_рекомендации.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации CustomAttributes)
        [StrLen(255)]
        public virtual string Выводы_и_рекомендации
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации Get start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации Get start)
                string result = this.fВыводы_и_рекомендации;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации Get end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации Set start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации Set start)
                this.fВыводы_и_рекомендации = value;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации Set end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Выводы_и_рекомендации Set end)
            }
        }
        
        /// <summary>
        /// Операционная_система.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчетОТестПК.Операционная_система CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчетОТестПК.Операционная_система CustomAttributes)
        [StrLen(255)]
        public virtual string Операционная_система
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Операционная_система Get start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Операционная_система Get start)
                string result = this.fОперационная_система;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Операционная_система Get end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Операционная_система Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Операционная_система Set start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Операционная_система Set start)
                this.fОперационная_система = value;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Операционная_система Set end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Операционная_система Set end)
            }
        }
        
        /// <summary>
        /// результаты_тестирования.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования CustomAttributes)
        [StrLen(255)]
        public virtual string результаты_тестирования
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования Get start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования Get start)
                string result = this.fрезультаты_тестирования;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования Get end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования Set start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования Set start)
                this.fрезультаты_тестирования = value;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования Set end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.результаты_тестирования Set end)
            }
        }
        
        /// <summary>
        /// Тестируемые_приложения_и_игры.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры CustomAttributes)
        [StrLen(255)]
        public virtual string Тестируемые_приложения_и_игры
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры Get start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры Get start)
                string result = this.fТестируемые_приложения_и_игры;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры Get end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры Set start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры Set start)
                this.fТестируемые_приложения_и_игры = value;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры Set end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.Тестируемые_приложения_и_игры Set end)
            }
        }
        
        /// <summary>
        /// Т ч отчет о тест ПК.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК CustomAttributes)
        [PropertyStorage(new string[] {
                "ОтчетОТестПК"})]
        [NotNull()]
        public virtual IIS.Inzhener5.ОтчетОТестПК ОтчетОТестПК
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК Get start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК Get start)
                IIS.Inzhener5.ОтчетОТестПК result = this.fОтчетОТестПК;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК Get end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК Set start)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК Set start)
                this.fОтчетОТестПК = value;
                // *** Start programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК Set end)

                // *** End programmer edit section *** (ТЧОтчетОТестПК.ОтчетОТестПК Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧОтчетОТестПКE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧОтчетОТестПКE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧОтчетОТестПКE", typeof(IIS.Inzhener5.ТЧОтчетОТестПК));
                }
            }
            
            /// <summary>
            /// "ТЧОтчетОТестПКL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧОтчетОТестПКL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧОтчетОТестПКL", typeof(IIS.Inzhener5.ТЧОтчетОТестПК));
                }
            }
        }
    }
}
